### ISSUE TITLE
backport zodbconvert incremental fixes to 1.6

### ISSUE THREAD

**Issue by mamico** [zodb/relstorage#109]
@jamadden is possible to commit (at least) #22 changes on 1.6 branch, and make a 1.6.1 release?
Many people still using ZODB3 and are not ready for ZODB 4 (i.e. people using Plone). thanks.

**Comment by jamadden** [comment]
I would review a PR that does that.

**Comment by jamadden** [comment]
Note that the 1.6.0 branch does not have CI or the test infrastructure to fully test such changes, so it's risky.

AFAICS, ZODB 4 is pretty much a drop in replacement for ZODB 3. If you're depending on the ZODB3 package, you are actually getting ZODB 4, unless you've manually pinned to older versions---which should be easy to upgrade.

**Comment by jamadden** [comment]
Another option is to make use of buildout's little-known, less-used ability to specify egg versions on a part-by-part basis. You could use one part with a newer RS/ZODB just to install zodbconvert.

**Comment by mamico** [comment]
Hi @jamadden thanks for you response and suggetions (sorry for my late reply). 

I use relstorage for Plone installations and at the moment AFAIK, Plone doesn't run with ZODB 4 (and if someone are working on it, is not ready for production).

So my idea is that Relstorage 1.6.*  sould continue to live with hotfix and minimal patch at least until there are many users that use it (like now).

I'm backport-ing some fix (#22, #30) and verifying the tests here: https://github.com/mamico/relstorage/tree/1.6 

My goal is to have a 1.6.1 version with these fixes at least for my own use.

If may also be helpful to other people who use relstorage (at least with Plone 4/5), I can make a (unique) PR at the end of this work or even make individual PR for each backport.

What do you think?

**Comment by jamadden** [comment]
I have no problem accepting and releasing bugfixes (only) for the 1.6 branch *if* they are tested (and don't reduce code coverage). I'm very wary of making changes to what is (and has been) a stable branch for a long time, so the very first step is to enable CI and coverage reports for the 1.6 branch. Then we can merge minimal patches. Oracle changes are less likely to get accepted in a timely fashion because I'll have to manually verify them, which requires spinning up an Oracle VM.

For the `--incremental` option in particular, though, I don't know if it's worth the effort. Unless I'm forgetting something, it should be pretty simple to install a modern version of RelStorage side-by-side with the 1.6 version (using either buildout or a virtualenv) and use the fixed zodbconvert. The data storage format (schema) hasn't changed, and RelStorage doesn't peek at the pickle data (with the possible exception of the root?) so unless there are all kinds of weird storage wrappers configured, zodbconvert doesn't need access to any user code.

FWIW (I'm not a plone guy), on a lark I tried Plone 5.0.5 with current ZODB today. I was encouraged by the result. It was simple to install after changing the version pins. I only ran into one minor incompatibility (which I admit I forgot about), which is that OOBTree doesn't allow `None` as a key anymore, which impacted indexes. I patched it locally, and [it's been fixed upstream](https://github.com/zopefoundation/Products.ZCatalog/issues/5), although I don't know what happens to existing data in a site with such a BTree...I know there's ongoing work to update other ZTK deps (e.g., https://github.com/plone/Products.CMFPlone/issues/1351)  but updating (or allowing) just this version [seems pretty doable](https://github.com/plone/buildout.coredev/pull/137).

**Comment by jamadden** [comment]
CI and coverage reports have been enabled for the 1.6 branch thanks to #113 and #114. (Woo!)

The next step would be a PR to pull in this series of changes (from test_zodbconvert.py history) to 1.6:
- 4ce0b3dc603d73f906b200f627a0c983cda67a55
- 7825a8d70fca1ec0245e193221b45c29139a71d4
- 5ca7aab1ca87c646d615c9ca69e1c3fdae0dc9fa
- a07e8f7fad581dbadc5be10cdebaf8d5014e811d
- 27df4b2b8325efff1ca251cb6edeba9c796d3081
- b7423274d499fe5bed6e847ec48dd5d493dc5c96

**Comment by mamico** [comment]
thanks @jamadden. I'll open the others PR as soon as possible.

**Comment by jamadden** [comment]
@mamico Are you planning anything else or are you ready for a 1.6.1 release?

**Comment by mamico** [comment]
@jamadden I have another PR for backporting #30 (Oracle installation doesn't "pack" using relstorage 1.6.*)

**Comment by jamadden** [comment]
OK, it's merged. I'll do a release.

**Comment by mamico** [comment]
@jamadden thanks. IMO could be useful to have on pypi something like https://pypi.python.org/pypi/ZODB3 with both (1.* and 2.*) branches visible, so people using ZODB3 known that there is a branch for him.

**Comment by jamadden** [comment]
1.6.2 has been released with these PRs.
