### ISSUE TITLE
zodbconvert with --clear against large existing RelStorage takes a long time

### ISSUE THREAD

**Issue by mcdonc** [zodb/relstorage#16]
Using master plus ZODB 4.X, `zodbconvert` output of  a database where the target RelStorage already held several million objects, and the source FileStorage did as well:

```
2014-06-23 06:10:50,597 [zodbconvert] INFO Storages opened successfully.
2014-06-23 06:10:50,597 [zodbconvert] INFO Clearing old data...
^C
```

The ^C was pressed six hours later.  I'm still waiting for the process to be aborted.  The resource usage on the machine was light (no swapping).  It seems as if the code to clear the database hadn't completed, and I'd contend that it should have within six hours.

**Comment by jamadden** [comment]
This makes sense to me and is the behaviour I would expect (given the current implementation) when clearing a database that has several million objects. (Obviously it's not ideal.)

Currently, *all* the tables RelStorage users are simply "DELETE FROM" all together in a single transaction which is then committed. "DELETE FROM" is a DML statement, and as such, interacts with transactions/MVCC/ACID/whatever you want to call it...in addition to verifying all the foreign key constraings in this transaction, the database has to ensure that any other connections that *might* open can still see all the data in a consistent state, in case the DELETEing transaction rolls back, right up until commit. This can often require a lot of IO if the number of rows being deleted is large (Oracle copies to "undo segments"). Even if we get to commit this transaction, there's a lot of IO that has to be done to update indexes and rows on disk. Multiply "several million" (more if you preserve history) by 5 or so tables, and it adds up quick.

When the process is killed, the database has to rollback that transaction, which again typically involves lots of I/O to reverse what it was in the middle of deleting (depending on implementation). (Restarting the server can act as a forced checkpoint, discarding temporary state and going directly back to source files; again, depending on implementation.)

Now, most databases offer some sort of "TRUNCATE" command that can be used to avoid the transactional interaction and make clearing a table very fast with no I/O overhead. This has some downsides, though:

- That command may be spelled differently across databases (I assume)
- It may have different restrictions across databases. For example, in Oracle, you can't TRUNCATE a table that involves foreign key references (which RelStorage uses) without disabling the relevant constraints (which again may be a database specific command).
- TRUNCATing a table may release all the storage space allocated to it (DELETE usually doesn't) which means that it's slower to grow it back up to size. In the zodbconvert case where all of the size allocations are happening in quick succession, that may be a substantial amount of overhead.

Only the first two prevent RelStorage from using such a command, but to do so, database-specific scripts would have to be written and tested. At the very least, knowledge of ordering and constraints would have to be added so that they could be appropriately disabled and enabled.

All in all, if the target RelStorage is very large, until (if and when) all that is implemented, I would recommend dropping and recreating the target schema (or tables if necessary) manually first.

**Comment by jamadden** [comment]
It was easy to fix this for PostgreSQL so I merged that.

**Comment by jamadden** [comment]
Implementing this for MySQL is tracked in #242, so I'll close this now.
