### ISSUE TITLE
Many source lines are too long

### ISSUE THREAD

**Issue by jimfulton** [zodb/relstorage#166]
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

Long lines hurt my eyes. :)

Any objection to a PR (or multiple PRs) to shorten them?

**Comment by jamadden** [comment]
Yes, I object to formatting changes just for the sake of formatting changes. For one thing it muddles history and "blame".

**Comment by jimfulton** [comment]
Actually separating formatting changes from other changes avoids muddling history and blame.

**Comment by jimfulton** [comment]
Do you wish to encourage or discourage contributions from me?

**Comment by jimfulton** [comment]
Let me ask this a different way.

Do you acknowledge that long lines are problematic?

**Comment by jamadden** [comment]
I do agree that lines that are too long *can* be a problem when working with multiple very narrow windows, or printing on paper using non-scaled resolutions. 

However, I also believe that lines that are too *short* can cause equal readability problems. It's just that instead of the machine doing the wrapping the human is manually doing the wrapping and introducing excessing backslashes or parenthesis and otherwise chopping up lines in ways that break the flow.

The currently enforced limit is 160 characters. That number is pretty much arbitrary, chosen to pass with the code as it existed when the limit was introduced. 

PEP8 allows for a limit of 100 characters. (That happens to be what my team normally uses and what my editor starts warning about by default.) There are 30 such lines in the codebase now. 

What if we went with 100 as a limit, adjusted those 30 lines, and changed the enforcement to be 100?

**Comment by jimfulton** [comment]
That's a reasonable compromise.
