### ISSUE TITLE
Why does relstorage use separate read and write connections.

### ISSUE THREAD

**Issue by jimfulton** [zodb/relstorage#170]
This is related to #125.

A basic idea of RelStorage is that we rely on the underlying DB's MVCC, except that we don't.

We sort of do for reads, but we still check for conflicts ourselves. And manage locks. :(

If we just used a single connection we could do away with locks, couldn't we? At least in a history-free-like configuration?

I imagine this was tried and rejected for good reason. It would be interesting to know what those reasons were, perhaps in the wiki here or in a checked in file.  

OTOH, I could imagine that the traditional ZODB history-preserving model got in the way.  Maybe there's a simpler model for applications that don't need time travel.

**Comment by jamadden** [comment]
The read connection is point-in-time as-of when you begin the transaction, relying on the backing RDBMS's MVCC to provide that point-in-time view. That won't work for the write connection which needs to be current with the actual state of the database as of when you commit, in order to check for and remedy conflicts. The lock is necessary to be sure that conflict resolution occurs in an ordered sequence.

**Comment by jamadden** [comment]
Note that the read connection will *never* be able to see any conflicts because by definition it's already stuck at some point in the past. Whether or not it will be able to actually commit changes to rows may depend on the state of other transactions, but getting a commit exception from the database  doesn't do us much good, since that aborts the transaction, clears temporary tables, etc, all before we could attempt conflict resolution---and now we have no way to replicate the state as-of when the read connection began.

**Comment by jimfulton** [comment]
For the sake of argument, let's say we don't care about conflict resolution.

The database itself will tell us if there are conflicts won't it?  We don't need to detect them ourselves.

**Comment by jamadden** [comment]
> For the sake of argument, let's say we don't care about conflict resolution.

Ok, but we really *do* care about conflict resolution. Still...

> The database itself will tell us if there are conflicts won't it? We don't need to detect them ourselves.

No, not necessarily. Working in `REPEATABLE READ` or `READ COMMITTED` modes (the two levels we need to work at), two transactions can update the same row; the second transaction will pause waiting for the first transaction to commit and then finish committing itself, thus effectively losing the first transaction's change (that or it might timeout). (I just verified this.)

If you are lucky enough to get a timeout or a PRIMARY KEY conflict error, then the state of the transaction is somewhat undefined/database specific, I think. Either it's exactly as it was, in which case *you can't see what the conflict was* (because it's ahead of you), or it's rolled back, in which case *you can't retrieve the old data* to be able to resolve the conflict. The first scenario you can work around...by using a second connection (which is basically what we do).

**Comment by jamadden** [comment]
MySQL has the former behaviour on an error: it leaves the state of the transaction as it was.

PostgreSQL, OTOH, does the opposite and implicitly aborts the transaction and accepts no further queries until you begin a new transaction; the state of the transaction is irrecoverable.

I can't remember what Oracle does off the top of my head (and I don't feel like spinning up a VM right now). Knowing it, something completely different 😜

**Comment by jimfulton** [comment]
On Fri, Mar 3, 2017 at 4:45 PM, Jason Madden <notifications@github.com>
wrote:

> For the sake of argument, let's say we don't care about conflict
> resolution.
>
> Ok, but we really *do* care about conflict resolution. Still...
>
Newt might not.  After all, if you don't use catalogs, you eliminate the
biggest source of conflicts.  And if by using a lighter implementation,
you'd be able to go much faster, you might accept the occasional conflict.
It's not as if we resolve all conflicts now.

> The database itself will tell us if there are conflicts won't it? We don't
> need to detect them ourselves.
>
> No, not necessarily. Working in REPEATABLE READ or READ COMMITTED modes
> (the two levels we need to work at),
>
Why do we *need* to work with those.

BTW, PG load connections use serializable.  Store connections use read
committed, but they rely on locks.

We could just open with serializable or possibly even repeatable read and
be done with it.
(I'm a bit foggy on the difference between the two in PG. Informally
playing with this, I haven't been able to provoke different behavior.)


> two transactions can update the same row; the second transaction will
> pause waiting for the first transaction to commit and then finish
> committing itself, thus effectively losing the first transaction's change
> (that or it might timeout). (I just verified this.)
>
At what isolation level did you verify this?

I just verified getting a conflict from PG at both serializable and
repeatable read. :)

I do see a delay in updates when there is a conflict, but that isn't any
worse than delays we have now waiting for commit locks.

**Comment by jimfulton** [comment]
https://www.postgresql.org/docs/current/static/transaction-iso.html

I suspect that the difference between repeatable read and serializable in PG would affect Newt (but might not matter for some use cases), but not ZODB itself.

BTW apologies for being PG focussed, but that's all I care about. :)

**Comment by jamadden** [comment]
>>  No, not necessarily. Working in REPEATABLE READ or READ COMMITTED modes
>> (the two levels we need to work at),
> Why do we *need* to work with those.

I had left out the word "least." We need to work *at least* at those levels. SERIALIZABLE is obviously a level beyond either of them. Interestingly, for whatever reason, MySQL's load connection just uses REPEATABLE READ, not SERIALIZABLE.

The practical difference, BTW, is with rows that you *don't* read, i.e., rows that are added. SERIALIZABLE won't show them, REPEATABLE will.

> At what isolation level did you verify this?

Both of them, *in MySQL* because that's what I had open. In PostgreSQL, I do (eventually) get a conflict with both levels. 

The MySQL case eventually times out if the first transaction doesn't commit. PostgreSQL doesn't seem to timeout, at least not for several minutes. That could pose a problem (the locks we use now have tunable timeouts).

I spun up my Oracle VM to test. Oracle behaves like MySQL (second transaction wins) for REPEATABLE READ and READ COMMITTED.

**Comment by jamadden** [comment]
> Newt might not.  After all, if you don't use catalogs, you eliminate the
> biggest source of conflicts. 

BTrees are also the basis of folders and other such containers. Even without catalogs those still conflict and they're commonly resolvable. 

zope.minmax objects also conflict and resolve often in some applications.

> And if by using a lighter implementation, you'd be able to go much faster, 

It's not obvious to me that there is a lighter implementation that would be "much faster", even if we're just talking about PostgreSQL. The time should be dominated by the IO, and that would be basically the same. At most you eliminate the one query that's used to detect conflicts (which would return nothing, because we're optimizing for the case that there are no conflicts) and probably the query that's used to lock tables...but those didn't ever show up in my profiling as hot spots.

**Comment by jimfulton** [comment]
On Fri, Mar 3, 2017 at 6:01 PM, Jason Madden <notifications@github.com>
wrote:

> Newt might not. After all, if you don't use catalogs, you eliminate the
> biggest source of conflicts.
>
> BTrees are also the basis of folders and other such containers. Even
> without catalogs those still conflict and they're commonly resolvable.
>
How conflicty is application dependent.

> zope.minmax objects also conflict and resolve often in some applications.
>
Yup.

And if by using a lighter implementation, you'd be able to go much faster,
>
> It's not obvious to me that there is a lighter implementation that would
> be "much faster", even if we're just talking about PostgreSQL. The time
> should be dominated by the IO, and that would be basically the same.
>
Unless it's dominated by locks, which I consider likely, but it's hard to
say for sure without trying it. Shootout should actually be a good test of
the best case scenario for this approach.


> At most you eliminate the one query that's used to detect conflicts (which
> would return nothing, because we're optimizing for the case that there are
> no conflicts) and probably the query that's used to lock tables...but those
> didn't ever show up in my profiling as hot spots.
>
You eliminate the locks. You also eliminate the temporary tables, and all
of the IO that goes with them. (Although I expect all of that "IO" is
actually in RAM.)

You also get rid of the need for upserts, as you know (based on the old
serial) whether an object is new or not.

**Comment by jamadden** [comment]
> Unless it's dominated by locks, which I consider likely, but it's hard to
> say for sure without trying it. Shootout should actually be a good test of
> the best case scenario for this approach.

Ok, good thought, We can run shootout, having `hold_commit_lock` being a complete no-op so we can measure the difference it alone makes. These are all using 6 processes and a local PG 9.6.2 server (on an 4-core 8-hyperthreads machine).

(Spoiler alert: I couldn't measure a significant difference at this load level.)

First, the stock 1,000 objects of 96-bytes test. Here's the numbers **with** the lock:

```
Testing postgresql with objects_per_txn=1000, object_size=96, mappingtype=<class 'persistent.mapping.PersistentMapping'> and concurrency=6 (threads? False)
  Running 1/3... add 0.2024s, update 0.1865s, warm 0.2023s, cold 0.2230s, hot 0.0618s, steamin 0.0015s
  Running 2/3... add 0.1832s, update 0.1572s, warm 0.2226s, cold 0.2284s, hot 0.0602s, steamin 0.0018s
  Running 3/3... add 0.1896s, update 0.1486s, warm 0.2002s, cold 0.2170s, hot 0.0588s, steamin 0.0017s

Results show objects written or read per second. Mean of 3

** concurrency=6 **
"Transaction",                postgresql
"Add 1000 Objects",                31294
"Update 1000 Objects",             36565
```

And here they are **without** the lock:

```
Testing postgresql with objects_per_txn=1000, object_size=96, mappingtype=<class 'persistent.mapping.PersistentMapping'> and concurrency=6 (threads? False)
  Running 1/3... add 0.1748s, update 0.1499s, warm 0.1971s, cold 0.2617s, hot 0.0841s, steamin 0.0021s
  Running 2/3... add 0.1948s, update 0.2327s, warm 0.2963s, cold 0.2699s, hot 0.0658s, steamin 0.0017s
  Running 3/3... add 0.1715s, update 0.1455s, warm 0.1962s, cold 0.2107s, hot 0.0589s, steamin 0.0015s

Results show objects written or read per second. Mean of 3

** concurrency=6 **
"Transaction",                postgresql
"Add 1000 Objects",                33263
"Update 1000 Objects",             34088
```

So add got a bit faster, but updating got almost the same amount slower. But both results are within the margins.

Here's the more realistic case of 100 objects that are slightly bigger (256 bytes):

**With** the lock:
```
Testing postgresql with objects_per_txn=100, object_size=256, mappingtype=<class 'persistent.mapping.PersistentMapping'> and concurrency=6 (threads? False)
  Running 1/3... add 0.0514s, update 0.0309s, warm 0.0320s, cold 0.0298s, hot 0.0072s, steamin 0.0004s
  Running 2/3... add 0.0515s, update 0.0325s, warm 0.0313s, cold 0.0311s, hot 0.0076s, steamin 0.0004s
  Running 3/3... add 0.0503s, update 0.0322s, warm 0.0326s, cold 0.0310s, hot 0.0074s, steamin 0.0004s

Results show objects written or read per second. Mean of 3

** concurrency=6 **
"Transaction",               postgresql
"Add 100 Objects",                11749
"Update 100 Objects",             18829
```

**Without** the lock:
```
Testing postgresql with objects_per_txn=100, object_size=256, mappingtype=<class 'persistent.mapping.PersistentMapping'> and concurrency=6 (threads? False)
  Running 1/3... add 0.0516s, update 0.0327s, warm 0.0342s, cold 0.0337s, hot 0.0082s, steamin 0.0004s
  Running 2/3... add 0.0519s, update 0.0314s, warm 0.0317s, cold 0.0316s, hot 0.0073s, steamin 0.0004s
  Running 3/3... add 0.0586s, update 0.0371s, warm 0.0327s, cold 0.0322s, hot 0.0077s, steamin 0.0004s

Results show objects written or read per second. Mean of 3

** concurrency=6 **
"Transaction",               postgresql
"Add 100 Objects",                11100
"Update 100 Objects",             17778
```

Here everything shows a tiny bit slower, but definitely within the margins.

So at least at this concurrency level, in this test where there are never any conflicts, the commit lock doesn't appear to be a substantial issue. Or if it is, the locks on individual rows (and I don't think we should actually have any) make up for it.

Note that this was still using a `REPEATABLE READ` store connection. I tried to use just one connection (re-use the load connection, which is `SERIALIZABLE`) and ran into unexpected ConflictErrors on the root object. I tried to make the store connection `SERIALIZABLE` (which I think it would have to be if this was going to work) and ran into this error:

```
psycopg2.extensions.TransactionRollbackError: could not serialize access due to read/write dependencies among transactions
DETAIL:  Reason code: Canceled on identification as a pivot, during conflict in checking.
```

**Comment by jimfulton** [comment]
On Fri, Mar 3, 2017 at 6:55 PM, Jason Madden <notifications@github.com>
wrote:

...
>
> So at least at this concurrency level, in this test where there are never
> any conflicts, the commit lock doesn't appear to be a substantial issue.
>
The itch I'm trying to scratch here is allowing applications to scale
writes horizontally, with many concurrent writers.  As things stand now,
everyone lines up at the global lock even if they're writing different
objects.

A key issue here is that ZODB requires a global timestamp that reflects
transaction commit order.  It relies on this for client synchronization.
At some point there *has* to be a global lock to service that. :-/

Oh, look:

https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#Commit_timestamp_tracking

If that does what I think it does.....

I think it does, because it seems to be motivated by replication use cases
which is essentially ZODB's need. (Clients are essentially database
replicas.)

To my surprize, that can be enabled in AWS RDS.

I'm sure there's a performance hit, but ...

I'll have to play with this.

**Comment by jimfulton** [comment]
On Sat, Mar 4, 2017 at 8:40 AM, Jim Fulton <jim@jimfulton.info> wrote:
...

> Oh, look:
>
> https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_
> 9.5#Commit_timestamp_tracking
>
> If that does what I think it does.....
>

Nope:

http://stackoverflow.com/questions/33943524/atomically-set-serial-value-when-committing-transaction

but there should be a way to leverage xmin::text::bigint (along with other
information to deal with wraparound).  This would mean, however, that tids
would no longer be timestamps.

**Comment by jimfulton** [comment]
Well, this was fun, but it left the domain of RelStorage a while ago. :)

**Comment by jamadden** [comment]
Too bad, that was a fun exercise.

#27 may be related.
