### ISSUE TITLE
Relstorage + Oracle does not work

### ISSUE THREAD

**Issue by rafaelbco** [zodb/relstorage#172]
I'm using Plone + Relstorage + Oracle (versions bellow). When committing the first transaction I get the following traceback:

    Traceback (most recent call last):
      File "/media/rafaelbc/data/buildout/eggs/collective.logbook-0.9.0-py2.7.egg/collective/logbook/events.py", line 81, in handleTraceback
        transaction.commit()
      # (...)
        self._prepare_tid()
      File "/media/rafaelbc/data/buildout/eggs/RelStorage-1.6.3-py2.7.egg/relstorage/storage.py", line 737, in _prepare_tid
        adapter.locker.hold_commit_lock(cursor, ensure_current=True)
      File "/media/rafaelbc/data/buildout/eggs/perfmetrics-2.0-py2.7.egg/perfmetrics/__init__.py", line 133, in call_with_metric
        return f(*args, **kw)
      File "/media/rafaelbc/data/buildout/eggs/RelStorage-1.6.3-py2.7.egg/relstorage/adapters/locker.py", line 159, in hold_commit_lock
        True,
    DatabaseError: ORA-03115: unsupported network datatype or representation

I traced the problem to the following call on `locker.py`:

        status = cursor.callfunc(
            "DBMS_LOCK.REQUEST",
            self.inputsize_NUMBER, (
                self.commit_lock_id,
                6,  # exclusive (X_MODE)
                timeout,
                True,
            ))

It seems cx_Oracle's `callfunc` function does not work with boolean parameters. My workaround was to create a stored procedure:

        create or replace procedure lock_request
        (
          id in INTEGER,
          timeout in INTEGER,
          status out INTEGER
        ) as
        begin
          status := dbms_lock.request(id, 6, timeout, true);
        end lock_request;

And monkey patch the `OracleLocker.hold_commit_lock` method to call this procedure instead.

    status = cursor.var(cx_Oracle.NUMBER)
    try:
        cursor.callproc(
            'trt3_lock_request',
            (self.commit_lock_id, timeout, status)
        )
    status = int(status.getvalue())

I'd love to see this fixed but I do not consider myself an Oracle "expert" in order to do this. I was able to workaround the issue but I don't know if this is the best approach.

Versions:

Plone = 4.3.7
ZODB3 = 3.10.7
Relstorage = 1.6.3
cx_Oracle = 5.2.1
Oracle = 11.2.0.4.0
instantclient = 12.2.0.1.0

**Comment by jamadden** [comment]
The release notes for cx_Oracle state that booleans have been acceptable arguments for `callproc` [since 4.3](http://cx-oracle.readthedocs.io/en/latest/releasenotes.html#version-4-3), which appears to have been around 2007 or so.

So far as I can tell, the basic code that cx_Oracle uses to format boolean parameters [hasn't changed much](https://bitbucket.org/anthony_tuininga/cx_oracle/src/fe4ff600b27b881d5372ebcd5573daae21faf97d/Cursor.c?at=4.3.1&fileviewer=file-view-default#Cursor.c-1252) since then. The major difference is that now, the special formatting is only done [when cx_Oracle was built against an older client version](https://bitbucket.org/anthony_tuininga/cx_oracle/src/1a6c77089c453202cd687de7a5c8cb06aca4c35d/Cursor.c?at=default&fileviewer=file-view-default#Cursor.c-1450) (prior to version 12).

Is it possible that the client version you're now using at runtime is different than the client version that built your cx_Oracle egg (you appear to be using buildout and building from source)? Specifically an older version?

**Comment by jamadden** [comment]
Ahh, actually, I think it may be that your client is *newer* than the database you're hitting. If you build with client=12, but connect to an older server, the boolean support that was added in cx_Oracle 5.2.1 may not work correctly.

I think your options might be to either (1) downgrade to cx_Oracle 5.2 or (2) build 5.2.1 against a client version that matches your database version (11).

**Comment by rafaelbco** [comment]
I will certainly try one of this options and report back. 

Which option do you think is the best in terms of performance and robustness? Im inclined to test option 2.

**Comment by jamadden** [comment]
Option 2 is also what I would recommend if possible.

If we can confirm that fixes the issue (and it really looks like it should), I will try opening an issue with upstream, but I suspect their response will be "compile with a client that matches the DB" anyway.

**Comment by jamadden** [comment]
cx_Oracle 5.3 was [just released](http://cx-oracle.readthedocs.io/en/5.3/releasenotes.html#version-5-3-march-2017). I don't think it does anything to resolve this cross-version problem.

However, the current master (what they're calling 6.0) [determines the client version at runtime](https://github.com/oracle/python-cx_Oracle/blob/master/src/Cursor.c#L1167) and so would fix this error.

So I think we can be pretty confident in what the problem is and what the two solutions are (use a different version, <=5.2,>=6.0, or compile with a compatible client version).

**Comment by rafaelbco** [comment]
I've just tested with cx_Oracle 5.2.1 and instantclient 11.2.0.4.0 and it works. 

To me the case is closed but I suggest adding something to the docs about this.

**Comment by rafaelbco** [comment]
Thanks for the awesome support! :1st_place_medal:
