### ISSUE TITLE
Sometimes getting segfault on exit with persistent cache with Relstorage 2.1a2

### ISSUE THREAD

**Issue by jimfulton** [zodb/relstorage#184]
A cron job started segfaulting after adding persistent cache:

    osfkarl@osfkarl10 ~/production/current $ bin/digest --frequency daily
    2017-05-03 09:55:48,683 INFO  [relstorage.cache.mapping][MainThread] Examined 188847 and stored 188847 items from <_io.BufferedReader name='/srv/osfkarl/production/97/var/pickle-cache/relstorage-cache-osf-karl.nkMYl9.rscache'> in 1.52034497261
    2017-05-03 09:55:50,308 INFO  [relstorage.cache.mapping][MainThread] Examined 188845 and stored 0 items from <_io.BufferedReader name='/srv/osfkarl/production/97/var/pickle-cache/relstorage-cache-osf-karl.ytE6Lf.rscache'> in 1.58140301704
    2017-05-03 09:56:00,732 INFO  [relstorage.cache.mapping][Dummy-2] Wrote 188872 items (80000107 bytes) to <_io.BufferedWriter name=3> in 1.34887313843. Total hits 38199; misses 53; ratio 0.998614451532
    Segmentation fault

The failure seems to be specific to this cron job. We haven't noticed it elsewhere.

Before digging further, I wanted to check whether this is a known issue or whether you had any hints on what to focus on.

RelStorage 2.1a2 Python 2.7 Linux Postgres 9.5

**Comment by jamadden** [comment]
No, I don't think we've seen that. 

There was a case awhile ago (<2.0.0b9) where we could generate corrupt cache files and then when we loaded them we couldn't read anything out of them, but I don't know of any recent-ish segfaults. 

Crashing after writing (closing), presumably when all activity on the cache has stoppd seems an odd time for a crash. My first guess would be that it happens when the instances are all dereferenced and collected by the GC, because deallocating CFFI objects has side effects that could potentially cause crashes.

It *might* have something to do with reading 0 items from the second cache file---is that always the case (that you read 0 items from a second cache file)? Does the problem go away if you set `cache-local-dir-read-count` to 1?

(BTW, that's a nice hit ratio you get. Does the ~3s startup penalty make it worthwhile for you?)

**Comment by jimfulton** [comment]
On Wed, May 3, 2017 at 11:12 AM, Jason Madden <notifications@github.com>
wrote:

> No, I don't think we've seen that.
>
> There was a case awhile ago (<2.0.0b9) where we could generate corrupt
> cache files and then when we loaded them we couldn't read anything out of
> them, but I don't know of any recent-ish segfaults.
>
> Crashing after writing (closing), presumably when all activity on the
> cache has stoppd seems an odd time for a crash. My first guess would be
> that it happens when the instances are all dereferenced and collected by
> the GC, because deallocating CFFI objects has side effects that could
> potentially cause crashes.
>
> It *might* have something to do with reading 0 items from the second
> cache file---is that always the case (that you read 0 items from a second
> cache file)? Does the problem go away if you set
> cache-local-dir-read-count to 1?
>

Nope.


> (BTW, that's a nice hit ratio you get.
>
Well, I've run this script multiple times, so the high ration isn't
surprising.

> Does the ~3s startup penalty make it worthwhile for you?)
>
It's not worth it for this script.  It's a small win, but ... segfault :)

It is a win for web processes as it provides quicker cache warming after
restarts.

We're still in the process of leveraging persistent caches, so It's unclear
what hit rates and benefits will ultimately be.

In any case, I'll do some more digging.

**Comment by jimfulton** [comment]
This does have something to do with GC.  This script uses the pyramid scripting helper which includes a closer function: 

https://github.com/Pylons/pyramid/blob/master/pyramid/scripting.py#L31

That calls ``pop`` on a thread-local manager:

https://github.com/Pylons/pyramid/blob/master/pyramid/threadlocal.py#L20

which basically makes a pyramid request and a "registry" garbage by removing (a dictionary containing) them from a list. I suppose this is important to do because some important thing happens as a result of GC(?).  (Obviously, that sounds pretty lame.)

If I remove this closer call *or* add:

    import gc; gc.collect()

to the end of the script, the segfault goes away. :(

**Comment by jimfulton** [comment]
On Wed, May 3, 2017 at 11:12 AM, Jason Madden <notifications@github.com>
wrote:
...

> My first guess would be that it happens when the instances are all
> dereferenced and collected by the GC, because deallocating CFFI objects has
> side effects that could potentially cause crashes.
>
Say what? :)

So are this is a cffi bug?  Is this related to the use of cffi to implement
the local cache?

**Comment by jamadden** [comment]
>> because deallocating CFFI objects has
>> side effects that could potentially cause crashes.

> Say what? :)

What I mean is that if the ownership of pointers/memory differs between "reality" and CFFI, then CFFI cleanups can cause issues due to use-after-free or similar.

> So are this is a cffi bug?  

Probably not? In my experience things that can actually be termed bugs in the CFFI implementation are rare.

> Is this related to the use of cffi to implement the local cache?

"Signs point to yes" if only because I've seen mistakes in CFFI uses lead to crashes before.

PyPy is often better than CPython 2 for debugging this kind of stuff, if only because it supports the -`Xfaulthandler` backported from Python 3 (and also because it rules out any other C-extension interactions).

**Comment by jimfulton** [comment]
I don't think it's going to be practical to try (harder with) this with pypy. Sorry.

**Comment by jamadden** [comment]
Ok. Did you install the manylinux wheels or build from source? I know of at least one other crash (in a different project) related to unexpected manylinux wheel incompatibility. We install from source.

**Comment by jimfulton** [comment]
On Wed, May 3, 2017 at 3:37 PM, Jason Madden <notifications@github.com>
wrote:

> Ok. Did you install the manylinux wheels or build from source? I know of
> at least one other crash (in a different project) related to unexpected
> manylinux wheel incompatibility. We install from source.
>
We install RelStorage from source.

(Also, this is a 32-bit system, fwiw.)

**Comment by jimfulton** [comment]
I hope I have an easy work around, so don't feel pressured to figure this out on my behalf, given that I can't give you helpful information.

**Comment by jamadden** [comment]
The persistent cache has been completely rewritten for RS3 and no longer uses CFFI, so I'm going to close this one. Feel free to re-open it or open a new issue if there are more crashes.
