### ISSUE TITLE
Using MyISAM vs InnoDB

### ISSUE THREAD

**Issue by jplouis** [zodb/relstorage#188]
Other than new_oid, are there reasons the other tables such as object_ref continue to use MyISAM?

**Comment by jamadden** [comment]
The tables that remain MyISAM are used during packing, which produces potentially large tables and does lots of IO. (IIRC it also does some interesting things with transactions.) So they're still MyISAM to reduce resource usage on the server since we don't need (and/or explicitly manage) advanced transactional semantics.

**Comment by jplouis** [comment]
Thanks for the reply!

**Comment by dpedu** [comment]
It would be nice if we could revisit this. Since RelStorage uses MyISAM, it is incompatible with MySQL's relatively new Group Replication feature as Group Replication only supports InnoDB.  My understanding is that Group Replication is the "face" of distributed mysql going forwards, so it would be nice to support this.

Because of this, I've actually tried blindly replacing this MyISAM directives in Relstorage's codebase with InnoDB - I have a fork with this work [over here](https://git.davepedu.com/dave/relstorage/commit/0b6990402f3db3b8c7a33681cb940b9a308367b4). I say blindly because I literally find-replace'd the string. I don't use RelStorage anywhere where high performance or large datasets are in play, so this is merely a proof of concept. Nor have I audited RelStorage's code to see if its design relies on MyISAM principles (is anyone aware of any?). 

Anyhow, it seems using only InnoDB is easily within the realm of possibility. Assuming one resolves the above points, are you opposed to merging a PR that adds a "default_engine" option that defaults to MyISAM and can be set to InnoDB?

**Comment by jamadden** [comment]
Thanks for bringing this up! I'd agree that it's probably time to revisit this topic. With RelStorage 3.0, we're officially dropping support for anything before MySQL 5.7 or so; previously we claimed support back to MySQL 5.0, but we haven't been testing on anything older than 5.7 for quite some time. Some of the original considerations [may have changed since 5.0](https://dev.mysql.com/doc/refman/5.7/en/converting-tables-to-innodb.html).

>  are you opposed to merging a PR that adds a "default_engine" option that defaults to MyISAM and can be set to InnoDB?

That's not an approach that seems especially tenable to me, for the simple reason that it doubles the size of the MySQL test matrix. I'd prefer to officially test and support one particular configuration of table  engines; folks are, as always, free to change things with `ALTER TABLE`, but "here there be dragons (maybe)."
