### ISSUE TITLE
Is there some plan when Relstorage 2.1 (RC or stable) will be released?

### ISSUE THREAD

**Issue by mamico** [zodb/relstorage#197]
@jamadden  Relstorage 2.1a2 seems to me on a stable situation, there are issues or doubt that block a RC or stable release? thanks

**Comment by jamadden** [comment]
2.1a2 [*is* released](https://pypi.python.org/pypi/RelStorage/2.1a2), is stable, and is usable. Please use it. 

"alpha" means things might get added or newly-added things might get changed. It doesn't speak to the stability of the core functionality. There are definitely more features I have planned, and potentially that some of the newly-added existing features might get changed (notably the persistent caching structures). 

"beta" means there will still be bug fixes, but the functionality is set: no new features or changes to existing or newly-added features.

"release candidate" ("rc") means no more bug fixes---there should be no changes between the last rc and the final .0.

I want to reserve the ability to make those alterations as necessary, and I can't do that if I've called them "beta", "rc" or "final." I could add new features by bumping the minor number (1 -> 2), but I couldn't break in any way (for example, tweak the configuration) the ones that have been released, not before "3.0"---and major version jumps like that tend to scare people, especially in a project with a long tradition of small version number changes like this one.

I suppose we could do what Chrome does and just use a new major version number every week, leading to massively inflated version numbers that have no meaning, but that doesn't seem helpful to me. Though, some have argued that approaching releases in a more laissez faire fashion like that is more "agile," and maybe breaking changes and major version number bumps aren't a big deal. In contrast, though, I know some large and conservative organizations that use RelStorage and don't have a problem using 2.1a2 and then releasing 2.1a3 and 2.1b1 and then 2.1.0 to production---but even a minor version bump to 2.2 triggers extensive retesting and delays reaching production.

**Comment by mamico** [comment]
Thank you for your clarification.

**Comment by jimfulton** [comment]
On Wed, Feb 7, 2018 at 5:51 AM, Jason Madden <notifications@github.com>
wrote:

> 2.1a2 *is* released <https://pypi.python.org/pypi/RelStorage/2.1a2>, is
> stable, and is usable. Please use it.
>
Modern packaging tools properly make this hard, because pre-releases are
considered unstable and not used by default.

> "alpha" means things might get added or newly-added things might get
> changed. It doesn't speak to the stability of the core functionality. There
> are definitely more features I have planned, and potentially that some of
> the newly-added existing features might get changed (notably the persistent
> caching structures).
>
I think you're the only person who uses alpha this way.

> "beta" means there will still be bug fixes, but the functionality is set:
> no new features or changes to existing or newly-added features.
>
> "release candidate" ("rc") means no more bug fixes---there should be no
> changes between the last rc and the final .0.
>
Generally, prereleases are considered unstable.  Beta is less unstable than
alpha and also promises not to introduce functionality changes that might
introduce instability.

RC is the least unstable.

> I want to reserve the ability to make those alterations as necessary, and
> I can't do that if I've called them "beta", "rc" or "final." I could add
> new features by bumping the minor number (1 -> 2),
>
Yes. That's what you should do, ASAP.  Your argument was halfway reasonable
when RelStorage had been in alpha for a few weeks.

> but I couldn't break in any way (for example, tweak the configuration) the
> ones that have been released,
>
Right. So don't do that.  Or do it *now*, get a new alpha out and get this
done.

If you're implying you might make breaking changes, then you're saying that
alpha isn't really stable.

> not before "3.0"---and major version jumps like that tend to scare people,
> especially in a project with a long tradition of small version number
> changes like this one.
>
Yes, so don't make breaking changes.

> I suppose we could do what Chrome does and just use a new major version
> number every week, leading to massively inflated version numbers that have
> no meaning, but that doesn't seem helpful to me.
>
Yes. That would be extreme. Leaving a release in alpha for over a year is
also extreme. How about doing something that's not extreme?

> Though, some have argued that approaching releases in a more laissez faire
> fashion like that is more "agile," and maybe breaking changes and major
> version number bumps aren't a big deal. In contrast, though, I know some
> large and conservative organizations that use RelStorage and don't have a
> problem using 2.1a2 and then releasing 2.1a3 and 2.1b1 and then 2.1.0 to
> production---but even a minor version bump to 2.2 triggers extensive
> retesting and delays reaching production.
>
I don't see how asking people to use software in production that might
incur breaking changes is any different than asking them to use software
with constantly changing major versions.

I'm sorry, but they and you are doing it wrong.

2.1 has an important fix for Postgres users.

I'm trying to convince my current employer to use RelStorage, but they
would need to use the alpha version because of the Postgres fix and the
fact that it's been in alpha for over a year isn't helpful.

**Comment by jamadden** [comment]
I can see that we have a very different understanding of the meaning, value, and interpretation of version numbers, especially insofar as they relate to the history of this project. Those understandings have been shaped by our individual decades of experience in the software industry, and so are unlikely to change based on anything said here. 

In the interests of community and harmony, then, it was easy to just throw up something called "2.1.0" on PyPI. Enjoy! (And expect to see a 2.2a1 in the near-ish future, sometime after I get gevent 1.3a2 out the door 😉 )

**Comment by jimfulton** [comment]
Thanks! :)
