### ISSUE TITLE
Encoding issues in Plone, running Heroku.

### ISSUE THREAD

**Issue by FinnArild** [zodb/relstorage#198]
Getting the classic UnicodeEncodeError: 'ascii' codec can't encode character.

I am unsure where the actual error is, but I fixed it by cloning the repo and changing line 688 from:
            desc = str(transaction.description)
to:
            desc = str(transaction.description.encode('utf8'))

So that works for me ...

**Comment by jamadden** [comment]
Thank you for your report. Encoding to UTF-8 is indeed [what recent releases (2.0+) of RelStorage do](https://github.com/zodb/relstorage/blob/master/relstorage/storage.py#L806). Recent versions of the `transaction` package [also require `description` to already be a unicode string](http://transaction.readthedocs.io/en/latest/api.html#transaction.interfaces.ITransaction.description).

Prior to RelStorage 2, ZODB 5, and transaction 2 (IIRC), applications were responsible for making sure the metadata for a transaction could be stored (e.g., was already `bytes`, aka `str` on Python 2). The storage layers attempted to compensate if the application layer did not do this, but, as you can see, this didn't always work.

Other than upgrading to a recent RelStorage (and possibly ZODB+transaction), I can only recommend making sure that transaction metadata is encoded correctly. I know that older versions of Plone did not (nominally) support ZODB 5, but RelStorage 2.0 and RelStorage 2.1 are still tested with ZODB 4 (I don't know the support status of that in Plone). I know that the upcoming Plone 5.2 uses ZODB 5 and should work with RelStorage 2.0. Finally, I understand that the main reason that Plone defaults to an old ZODB is because of issues with None in BTrees, but that was fixed in BTrees 4.4.0, which is what allowed Plone 5.2 to default to ZODB 5; that's *probably* a drop-in upgrade for older Plone versions. (I am not a plone dev or plone user, just an observer.)

**Comment by FinnArild** [comment]
Thanks for the very thorough comment. I will try 2.x.x with my Plone 4 installations and failing that I will try fixing the code that leads up to this problem.
