### ISSUE TITLE
psycopg2 pip package will be renamed psycopg2-binary in 2.8

### ISSUE THREAD

**Issue by azmeuk** [zodb/relstorage#208]
relostorage [depends on psycopg2](https://github.com/zodb/relstorage/blob/master/setup.py#L119) package, but if I install psycopg2 from pip, I get this warning message:
```
...virtualenv/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
```
Can relstorage depend on either `psycopg2` or `psycopg2-binary`? Would you accept a pull request for this?

**Comment by jamadden** [comment]
The psycopg2 documentation specifically says [not to depend on `-binary`](http://initd.org/psycopg/docs/install.html#binary-install-from-pypi):

> If you are the maintainer of a publish[ed] package depending on psycopg2 you shouldn’t use psycopg2-binary as a module dependency. For production use you are advised to use the source distribution.

Perhaps there's some documentation we could update ('for local, testing, and CI usage, feel free to install `psycopg2-binary` instead of using the `postgresql` extra'), but it doesn't look like we should change our extra.
