### ISSUE TITLE
how to set mysql/mariadb storage engine in RelStorage

### ISSUE THREAD

**Issue by thigazi** [zodb/relstorage#25]
Hi people. 
I am using Plone and I am interisted to make use of RelStorage along with MariaDB. Instead of the standard InnoDB / XtraDB Engine, I'd love to make use of a different one at the time RelStorage is creating the tables. 

Could somebody of you please tell me how to accomplish that. 

best, Tamer Higazi

**Comment by jensens** [comment]
afaik the engine is fixed to innodb, so it needs minor enhancement here in order to chnage this. see
https://github.com/zodb/relstorage/blob/master/relstorage/adapters/schema.py#L63

**Comment by jamadden** [comment]
Configurable storage engines is an interesting idea. Other engines would have to be explored in some depth to make sure it doesn't compromise any of the guarantees that RelStorage needs (otherwise, why would it be configuring specific engines now?)

This is a long-term concept. Personally as a stepping stone, I'd like to see better separation of the databases from each other to make it easier to experiment with this kind of thing.
