### ISSUE TITLE
IDEA: Use PostgreSQL xmin and xmax system columns for mvcc and for letting VACUUM do the packing

### ISSUE THREAD

**Issue by do3cc** [zodb/relstorage#27]
This is for a now a RFC. After looking deeper into PostgreSQL and our Relstorage issues I started to wonder if Relstorage could not leverage the MVCC support in PostgreSQL directly.
I have NOT yet done a deeper look into Relstorage with regard to this, but I plan to
@saily @jensens

**Comment by saily** [comment]
+1 @hathawsh what do you think?

**Comment by jensens** [comment]
Overall it sounds like really good idea. I'd need to read myself into PostgreSQL docs to give valuable input.

I know RelStorage code up to some point and it is very generic in its base and uses kind of (and so named) adapters to do the database specific work. It dont know exact how much of it is generic and which parts are delegated to the adapters. To implement mvcc database-specific stuff it is eventually needed to refactor some of the code.

OT/FYI: at Plone conference we had a good discussion regarding performance, RelStorage and PostgreSQL. Overall there was an idea in the air to have a storage backend that is tailored for PostgreSQL only and uses its features in depth. We talked even about JSON pickles and using databses json-capabities up to some degree and such. This was just a rough (!) brainstorming, but showed that a modern PostGreSQL could be used in a much richer way than we do today. 
Same discussion, other topic: Why is RelStorage that much faster than ZEO-Server? Probably its  because of the usage of memcached. ZEO-Server itself is dumb and should be fast anyway. There could be room for major improvements on this side too.

**Comment by hathawsh** [comment]
I've never noticed xmin and xmax before.  They sound like an interesting way to accomplish MVCC, although just adding that to RelStorage would probably complicate it significantly.

I've been thinking about JSON pickles and pure Postgres (9.4+) as well. JSON would make the database queryable and much more compatible with other languages. The interesting part of JSON pickles is figuring out how to encode ZODB-like object references.

**Comment by hathawsh** [comment]
BTW, the way to completely fix the problems with idle transactions is to replace the ZODB.Connection class with something that doesn't expect storages to be quite so naive. We need a storage interface that can close (as needed) when the transaction ends.

**Comment by jimfulton** [comment]
WRT JSON: https://github.com/jimfulton/zodb-jsonb-experiment

**Comment by jimfulton** [comment]
I don't understand "We need a storage interface that can close (as needed) when the transaction ends."

In ZODB5, we could certainly call a hook when a connection is closed.

**Comment by jimfulton** [comment]
Ah.  Now I understand what this is about. :)

I spent some time thinking about this this morning.

See http://stackoverflow.com/questions/33943524/atomically-set-serial-value-when-committing-transaction

Need to figure out how to deal with wraparound.  Reading about this makes my head hurt, so I'm going to stop for a while. :)

This also has implications for _p_serial (aka tids).

**Comment by jimfulton** [comment]
I've continued to beat my head against this on and off.

It turns out that xmin and xmax really only apply at the record level, not the database level.  xmin only increases monotonically for individual primary keys, and even then only in repeatable read and serializable isolation levels. (It's probably more complicated than that, but I'll leave it at that for now.)

I find the names xmin and xmax misleading because visibility isn't based solely on comparison of transaction ids. The database keeps a table of open transactions, which are also invisible, even though they may have earlier transaction ids.

Note that these transactions ids are set before commit (on first insert/update/delete or when txid_current() is called), not at commit as with ZODB's tids.

This means that there's no single monotonically-increasing value we can use to poll for updates.
