### ISSUE TITLE
Final Release?

### ISSUE THREAD

**Issue by jensens** [zodb/relstorage#28]
Since there are no blockers open and several improvements done - what about a final 1.6.0 release?
We're using 1.6.0b3 in production since a year for many sites w/o any problems.
If you need any help releasing I'am happy to help out.

**Comment by jensens** [comment]
just found #22 would be a nice to have merge before final.

**Comment by peterjacobs** [comment]
what is the database you are running on? we have a (non-blocking) issue with packing on Oracle: https://github.com/zodb/relstorage/issues/30

**Comment by jamadden** [comment]
Perhaps we should consider release plans @jimfulton ?

Maybe something like:

- Release as-is for a 1.6 final. Since pip et al only install final releases by default this may get some more eyeballs on the current code and provide additional input for the next step:
- Get CI going and merge any small mergeable PRs (such as #18, #23, #22) for a 1.7 series.
- Merge the ZODB5 related work to a branch that becomes 2.0. 

I'm not sure where #31 belongs, it might straddle two boundaries. Last time I was running tests, which was for #23, everything was passing locally for me with the then-extent versions of ZODB (because I was working on those changes too.)

**Comment by jimfulton** [comment]
Gaaaa, sorry, I just saw this after merging the ZODB5 branch to master.  Is there a reason not to include ZODB5 support in 1.6.0?

I suppose release the commit just before my merge as 1.6.0 final. (Perhaps that corresponds to the last beta tag.) and release the ZODB5 work as 1.7.0b1.

I had much bigger plans for 2.0.  For 2.0, I was thinking of replacing IMVCCStorage with a simple connection pool. And replacing current polling-interval mechanism with poll in sync.

WRT CI, +1, aside from the fact that CI is a pain. :). Does travis suppore using Postgres or MySQL? Or is that why you were thinking of adding SQLite support?

**Comment by jimfulton** [comment]
BTW, it might be good to discuss this in #zodb on freenode.

**Comment by jensens** [comment]
settign up Travis CI with postgres is straight forward: https://docs.travis-ci.com/user/database-setup/

**Comment by jamadden** [comment]
My thought on #31 was that ZODB5 is a work in progress, not yet released. I know that we, at least, have been using the last beta tag of RelStorage with the current release of ZODB without any trouble. Given that we don't yet have any CI, that seemed like the safest course.

Yes, Travis supports both MySQL and Postgres. SQLIte is just a convenience for faster/easier development testing.

**Comment by jamadden** [comment]
2.0 was just a number I picked that was bigger than 1.7 :) If the ZODB5 changes are small and backwards compatible with ZODB4, I wouldn't have any objection to seeing them in a 1.x release.

**Comment by jamadden** [comment]
There's not a bot logging #zodb, is there? If not, I like the asynchronous nature of email/issue comments. I miss stuff on #gevent far too frequently (not that much goes on there)...

**Comment by jensens** [comment]
I think its good to stick to semantic versioning as defined at http://semver.org/ - since @jimfulton change is backward compatible but more than a bugfix, I'd say its a 1.7 and cant go into 1.6 release because this was already beta. 

I'd branch away the last beta tag on a 1.6.x branch (and do a release from there) and let master target 1.7.

**Comment by jimfulton** [comment]
So wrt 1.x releases, release the version tagged with 1.6.0b3 as 1.6.0.  Release master as 1.7.0b1. Possibly create 1 6.x release branch if you want to release existing PRs before 1.7.0.

Note that I consider a ZODB5 release (after a ZEO 4 release) this week likely.

**Comment by jamadden** [comment]
If a ZODB5 release is coming soon (cool!), then I would think that a 1.6.0 final release of RS is in order.

Not to bikeshed, but I would call the master release 1.7.0a1 because we (I) expect to be merging some of those open PRs and they provide new features/API additions.

I wouldn't see much need to "backport" them to a 1.6.x release because 1.7.x is expected to otherwise be a drop-in replacement...hmm, that may actually not be technically true, current RS master supports ZODB 3.7 but PyPy (and Python 3) support requires ZODB 4.

**Comment by jimfulton** [comment]
https://zope3.pov.lt/irclogs-zodb/

**Comment by jamadden** [comment]
I'm working on a 1.6.0 final release. Running the MySQL tests, I get a few test failures I don't remember from before ( #23). Two of them are definitely due to zodbpickle (those can be fixed up in the PyPy PR). One of them is a failure from a ZODB test that RelStorage runs:
```
======================================================================
FAIL: checkUndoCreationBranch1 (relstorage.tests.testmysql.HPMySQLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "//python2.7/site-packages/ZODB-4.3.1-py2.7.egg/ZODB/tests/TransactionalUndoStorage.py", line 185, in checkUndoCreationBranch1
    b'\x7f\xff\xff\xff\xff\xff\xff\xff')
AssertionError: KeyError not raised
```

Which is this:
```python
        # Loading current data via loadBefore should raise a POSKeyError too:
        self.assertRaises(KeyError, self._storage.loadBefore, oid,
                          b'\x7f\xff\xff\xff\xff\xff\xff\xff')
```

That's a test that @jimfulton added in 4.3.1 (https://github.com/zopefoundation/ZODB/commit/5b18a710db75c4be1631c373e672cf9cfa254edb) for https://github.com/zopefoundation/ZODB/pull/64 So presumably this is also a bug in RelStorage that needs to be fixed, but it's not a new regression.

So I'll go ahead and make the release in spite of the failures.

**Comment by jamadden** [comment]
I've uploaded 1.6.0 to PyPI.
