### ISSUE TITLE
Cannot use postgresql zodburi resolver with psycopg-binary

### ISSUE THREAD

**Issue by azmeuk** [zodb/relstorage#342]
My understanding is that while `psycopg2-binary` might no be a good choice for production, it is ok to use it in unit tests. However with only `psycopg2-binary` installed, I cannot resolve a postgresql URI, as it explicitely requires `psycopg2`:

Is it a bug, or am I doing something wrong?

```bash
$ virtualenv env
$ env/bin/pip install zodburi relstorage psycopg2-binary
...
$ env/bin/python -c "import zodburi; zodburi.resolve_uri('postgres://foobar@localhost')"                                                                                                                                        
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/eloi/dev/yzodb/local.virtualenv/lib/python3.7/site-packages/zodburi/__init__.py", line 14, in resolve_uri
    resolver = ep.load()
  File "/home/eloi/dev/yzodb/local.virtualenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "/home/eloi/dev/yzodb/local.virtualenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/eloi/dev/yzodb/local.virtualenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psycopg2>=2.6.1; platform_python_implementation == "CPython" and extra == "postgresql"' distribution was not found and is required by the application
```
This ticket might be related to #208.

**Comment by jamadden** [comment]
Neither bug nor doing something wrong, that's just not a supported configuration.

**Comment by azmeuk** [comment]
Is it something easily enabled or is there some technical difficulties with this package?

**Comment by jamadden** [comment]
By "not supported" I mean that relstorage does not, and does not intend to, test the 'psycopg2-binary' distribution.

One could probably tweak the metadata to eliminate all mention of required drivers. But then if you didn't have the correct driver installed you'd just get a *different* error message with no clue about how to resolve it in a supported way. At least this error tells you how to fix it: install the 'postgresql' extra. 

One could also add a different URI entry point that referred to the 'psycopg2-binary' distribution as its requirement and then do something like `zodburi.resolve_uri('psycopg2_binary://host...')`. 

Then again, it could be said that a better way to allow enforcing a driver would be to make the URIResolver accept the 'driver' argument; arguably our 'NoDriversAvailableError' is pretty clear now and could possibly be made a bit more clear, making the requirement of an extra a bit redundant. I'll think about that a bit more and then probably do it 😄 

In the meantime, either of those other options would be easy to add to your own project. (If the entry point was named 'postgres', you could use the same URLs, but then `sys.path` order matters because of how `zodburi` and `pkg_resources.iter_entry_points` works; it would take a small patch to `zodburi.resolve_uri` to make it search for, and try, multiple entry points of the same name if the first one didn't resolve).
