### ISSUE TITLE
When Relstorage 3.5.0 final or beta?

### ISSUE THREAD

**Issue by tisto** [zodb/relstorage#487]
@jamadden first of all thanks for working on relstorage, it is a great product! :)

We are running relstorage with a database that is currently around 150 GB and it is growing fast (the client just started to create content). We would love to give the new enhancements (e.g. for a very large number of blobs) a shot. Though, relstorage 3.5.0a5 has been released in July:

https://relstorage.readthedocs.io/en/latest/changelog.html#a6-2021-07-21

and not seen much action since then. Since it is an alpha, we hesitate to try it out yet. Can you give us an idea when we can expect a beta or even final release of relstorage?

**Comment by jamadden** [comment]
I can't make any promises about release schedules at this time :(

I *can*, however, let you know that "alpha" is meant in the classic sense: there is more feature work to come (the big hoped-for feature was a shared-memory cache, but that's not completed); it's not meant in the "this is dangerous" modern sense.

I can also let you know that we're running the latest 3.5aX release in production, supporting numerous clients of varying sizes. Especially for larger clients it's been a great improvement.

**Comment by jamadden** [comment]
Well, there are still major hoped-for improvements for which the groundwork has been laid, but which are not yet implemented, but I'm making a release right now fixing the compiler flags and some other minor updates and calling it 3.5.0, because I have even less idea about when I'll be able to get those things done than I did 10 months ago.
