### ISSUE TITLE
pg8000 driver - AttributeError: 'Connection' object has no attribute 'in_transaction'

### ISSUE THREAD

**Issue by glautersv** [zodb/relstorage#495]
relstorage/adapters/postgresql/drivers/pg8000.py

line 246, in connection_may_need_commit
    return conn.in_transaction
AttributeError: 'Connection' object has no attribute 'in_transaction'

**Comment by mamico** [comment]
I had same issue today, changing here:

https://github.com/zodb/relstorage/blob/463450e822cb988905ae050e35913e1c91f6241a/src/relstorage/adapters/postgresql/drivers/pg8000.py#L246

```
- conn.in_transaction
+ conn._in_transaction
```

the problem seems resolved. But i Think that pg8000 changed many things after the Relstorage implementation. So could be other hiddens issues.

**Comment by jamadden** [comment]
Fixed in the upcoming RelStorage 4.
